### ISSUE TITLE
demo not working on main site

### ISSUE THREAD

**Issue by howardroark2018** [novius-os/novius-os#12]
well, I guess there is some password mismatch or something coz the login screen of the demo is not accepting the suggested username or password provided on the demo page. could you please check that?

**Comment by felixgilles** [comment]
Hi and thank you for reporting,

Unfortunately, the whole team is on vacation for Christmas. There is a reset every night at 1am Paris' time (7pm in NYC): I hope that next will solve the problem, otherwise I must look under the hood.

**Comment by Savageman** [comment]
Hello,

I just had a further look and the automatic reset doesn't seem to work properly (we changed the server and probably forgot something during the process). We'll have it fix when we come back from vacations.
Meanwhile, I did a manual reset and everything is working again for now.

Sorry for the inconvenience.
