### ISSUE TITLE
Anchor links not working

### ISSUE THREAD

**Issue by mvy** [novius-os/novius-os#13]
Hi! I've been creating templates recently and I now try to populate my pages.

I've ran into the following problem: 
1. Write some text in the WYSIWYG editor. 
2. Add an anchor
3. Add a link to this anchor

This should enable me to click on a link and get back to the anchor in the same page. However, it loads the main page instead (with #anchor concatenated) !
I've tested it with the original template for the same behaviour. 

I looked at the generated code and all is ok: but

**Diagnostic**: the `<base href="..">` is messing with the links.

**Question**: Is this necessary?

**Comment by felixgilles** [comment]
Hi,  
Thanks of this issue and this good description.  
I've push a fix in branch master/0.1.5:  
https://github.com/novius-os/core/commit/fc7dbca698c1c097f98d1ea07230a739159ef8bf

**Comment by mvy** [comment]
Tested the fix successfully. Thanks!
