### ISSUE TITLE
Problem on application removal

### ISSUE THREAD

**Issue by mvy** [novius-os/novius-os#17]
I created an application with the wizard. It seems that removing it also removed the other application from the list.

The applications are still working though. Some lost their icon on the desk (‘Build your app’ wizard, Forms, Users, Webpages, Applications manager, Media Centre). Only monkey and my accounts icon seems unaffected (see attch.).

It is not possible to reinstall the applications since the manager says template/launcher/enhancers of that name already exists. 

Image included. (The warning on the last image seems not to show everytime, maybe it's irrelevant)

From my knowledge of NOS, it might have something to do with `local/metadata/app_installed.php` which is now returning an empty array on my server.

![NosBug1](https://f.cloud.github.com/assets/757993/123692/b0b44af8-6ed2-11e2-9f0a-7652acfd8ef9.png)
![NosBug2](https://f.cloud.github.com/assets/757993/123689/a99b82a4-6ed2-11e2-8c05-adb0f55c8d2e.png)

**Comment by Savageman** [comment]
Good catch!

We already fixed it this morning! :)

To solve the problem, please delete every file from local/metadata, except 'app_installed.php' and 'namespaces.php', then re-install all the applications manually. It should work.
