### ISSUE TITLE
[Suggestion] Notification centre

### ISSUE THREAD

**Issue by mvy** [novius-os/novius-os#18]
Hi! I am doing some "How-To" and creating a very basic template. I saw that symlinks for static directory for an application is created if and only if the directory exists at when you install (or update) the application via the manager. 

This let me think that important notice may be written somewhere like a notification centre. An icon might (on/off) could suggest the administrators that new notification are available to check. 

The notifications (mostly errors) are already signalled by the mean of a "floating popup"  when the event occurs. There could be stored also in the notification centre for later review.

Here is some ideas of what should/could be logged: 
- Errors - Warning
- Application needing update (modified the metadata, added static repository)
- Requests for unexisting pages (404, ...) 
- New versions of NOS (and if they can be fast-forward or needs major maintenance) ?
- Other things ?

**Comment by mvy** [comment]
By the way, would suggestions be better on the forum rather than github issues?

**Comment by alefeuvre** [comment]
Hello Yves,

I'm sorry it took me five months to get back to you.
Many thanks for sharing. (Both GitHub and the forum are fine to submit ideas.)

Novius OS definitely lacks notifications mechanisms. The 'Forms' app, for instance, should be able to alert you when a new answer is received. So far our take on this was:
- Like on smartphone OS, apps could have a bubble attached showing the number of unread notifications
- \+ Widgets on the desktop for stats and/or activity feeds, as on the mock-up below (new UI project, more on this soon).

![nos-desktop-project](https://f.cloud.github.com/assets/1375051/782268/5bac2aa8-ea38-11e2-911d-3c2e07a170c2.png)

This said, your idea of a notifications centre is interesting too. I add this to our feature tracker. Don't expect a follow-up very soon, though. Novius OS D features don't include notifications. It might come with Novius OS E.

**Comment by mvy** [comment]
No problem! I'm just willing to drive some ideas when I get them. If you find different way to implement them I'm okay with this.

Good luck.
