### ISSUE TITLE
[Bug] Edit monkey and validate with keyboard

### ISSUE THREAD

**Issue by Pierrinho** [novius-os/novius-os#19]
I have a bug when I edit a monkey. I change the title and the URL of monkey, and I confirm by pressing 'Enter' on the keyboard. Here is a screenshot ;-)
![c0834ad9cd5de0e8fc57e4360459b21a](https://f.cloud.github.com/assets/2307724/167620/c466eb80-79dd-11e2-87d0-447e3adc418e.jpg)

**Comment by felixgilles** [comment]
Hi Pierre !

It's fixed. It's a big bug but a small cause : a forgotten type="button" which close the current tab when you click it. 
So the button has default type "submit". 
So when you press enter in a field, its click event was call

Thank !

**Comment by Pierrinho** [comment]
Great ! Thanks ;-)
