### ISSUE TITLE
Tabs are closing when I refresh them after a code modification

### ISSUE THREAD

**Issue by jiboule** [novius-os/novius-os#20]
Before that issue, I had an other one (less blocking though) :
- I have an oppened tab in NOS and I change a line in my code, I directly refresh my browser and if I do it too fast, an error message shows up and my tab is not shown. Therefore, if I wait a few seconds more, I don't have this issue anymore.

That was before, 

Now the tab is closing itself and the message "connection error" shows up.

This is quit disturbing I shall say don't you howdihow my taylor is among the middleclass ?

**Comment by felixgilles** [comment]
The problem is latency between the recording file and its availability in the web server (working on a network drive). The tab sends a 404.

In Novius OS 0.2, in admin, when a tab encounter a 404 error, it closes (to force a reset).

The problem is therefore the backup latency.
