### ISSUE TITLE
Installation invitation

### ISSUE THREAD

**Issue by Unibozu** [novius-os/novius-os#22]
Right after installing NoviusOS 0.2 using the SH installer, the first page prompt to create a .htaccess file.
After I've done it, I hit F5 to refresh this page.

The page disappeared and displayed the front page with some errors in the background. At this moment it is impossible to find again the installation URL !

**Comment by felixgilles** [comment]
Hi Clement,

We already are aware of this issue. In fact, after you create the .htaccess, you must click on the "Go to the install wizard" button, not refresh the page. But many user have this reflex.

Therefore, in the next version (7bc23daea658563bd8299fadb5d32b16aaaff0c3), the front page will detect that the install is not finish and will redirect you to the install wizard.

Currently, to resume the install, add install.php at the end of your URL. This will display the install wizard.
