### ISSUE TITLE
Links to documentation in the install process

### ISSUE THREAD

**Issue by Unibozu** [novius-os/novius-os#23]
These links : 
- https://github.com/novius-os/novius-os/wiki/%28EN%29-How-to-set-up-the-front-office
- https://github.com/novius-os/novius-os/wiki/%28EN%29-Applications

do not exist and Github ask me to create the pages

**Comment by felixgilles** [comment]
Hi Clément,

What version of Novius OS did you installed? In what step of install process did you see these links?

**Comment by Unibozu** [comment]
Hi, 

It is displayed on the front page after the installation (when there is no home page created in back office).

The two links after "I want an application" :
![noviusos-buglinks](https://f.cloud.github.com/assets/1690498/259595/e2fc2122-8cc1-11e2-97ca-f78a161a823b.PNG)

Cheers

**Comment by felixgilles** [comment]
It's fixed

Thank Clément !
