### ISSUE TITLE
Media center bug

### ISSUE THREAD

**Issue by mvy** [novius-os/novius-os#26]
Hi, 

It seems to be a problem with my media centre. I can upload `.tex` files, `.docx` file (probably images too) without problem. 

When I try to upload some PDF, the media centre fails to add it. I first though the size of the PDF was the cause, but even with a 5MB file I got an error. 

Sometimes it's just `Connection error`, but I got this one once: 

```
You have a problem here: Your Novius OS isn’t authorised to save files on this server. This is something your developer or system administrator can fix for you.
```

There is no further log in `logs/fuel/2013/04/04.php`. The apache log does not show any relevant information either. 

Is there a known issue with PDF files? Can't figure if this is a misconfiguration of my instance or not.

**Comment by mvy** [comment]
Update 1: I manage to upload PDF finally. Seems that 5MB was eventually too big. 
I could get a 990KB PDF online, but still no success with the others. I'll keep investigating.

**Comment by mvy** [comment]
Update 2: I found the problem for the size. My `nginx` settings was not allowing more than 1MB in the request body. I added a configuration line in the site file to take care of this. I also changed 

I still have the same error for the 6MB PDF file, but for the 12MB I also received a 

```
Please pick a file from your hard drive.
```

error. 

If figured out there was also a limit for apache. This has been taken care of. 

However, I still have the 

```
You have a problem here: Your Novius OS isn’t authorised to save files on this server. This is something your developer or system administrator can fix for you.
```

And no specific log for what happened. Is there a limit within novius-os configuration as well?

**Comment by mvy** [comment]
I isolated the error from the framework : 

In `novius-os/framework/applications/noviusos_media/classes/controller/admin/media.ctrl.php` line 125:

```
$_FILES['media']['tmp_name'] . " dest " . $dest);
```

The whole block being: 

```
120  // Write the file¬
121         if ($is_uploaded) {¬
122             // From upload¬
123             if (move_uploaded_file($_FILES['media']['tmp_name'], $dest)) {¬
124                 chmod($dest, 0664);¬
125             } else {¬
126                 \Log::error("move uploaded file failed: _FILES['media'] ".¬
127                 $_FILES['media']['tmp_name'] . " dest " . $dest);¬
128                 throw new \Exception(__('You have a problem here: Your Novius OS isn’t authorised to save files on this server. This is something your developer or system administrator can fix for you.'));¬
129             }¬
130         } else if ($is_renamed) {¬
131             // From existing file¬
132             \File::rename(APPPATH.$this->clone->get_private_path(), $dest);¬
133         }¬
```

From my logs, it seems that  `$_FILES['media']['tmp_name']` is empty.

Here is a dump of `$_FILES['media']` that I logged using `serialize` : 

```
  a:5:{s:4:"name";s:22:"TheseYvesStadlerBU.pdf";s:4:"type";s:0:"";s:8:"tmp_name";s:0:"";s:5:"error";i:1;s:4:"size";i:0;}
```

**Comment by Savageman** [comment]
The 'error' key is equal to 1. Which the documentation says: "UPLOAD_ERR_INI_SIZE : The uploaded file exceeds the upload_max_filesize directive in php.ini."

(from: http://www.php.net/manual/en/features.file-upload.errors.php).

**Comment by mvy** [comment]
Good catch. 
Working now. Thank you very much!

#### Summary :
- changed `post_max_size` in `php.ini`
- changed  `upload_max_filesize` in `php.ini`
- change `client_max_body_size` in the `nginx` configuration of my site (`location` section).
