### ISSUE TITLE
Warning when a page is displayed

### ISSUE THREAD

**Issue by Foine** [novius-os/novius-os#27]
![capture du 2013-05-03 11 48 37](https://f.cloud.github.com/assets/1659102/458518/d81de79c-b3d9-11e2-99d9-759f6d8bb940.png)
Hello !
Has you can see on the screenshot when I display some pages, I have a warning.
The page is displayed but the html structure is broken (all the html code in the head tag is now in the body... Don't know why...)
The problem do not append all the time. It's just some time, it append. I can't figure why...

**Comment by felixgilles** [comment]
It looks like a UTF8 problem.... a file, the DB ?

**Comment by felixgilles** [comment]
Hi @Foine, do you resolved your issue ?

**Comment by Foine** [comment]
Yes. I change my front framework and it never append again. I suppose that was the files but I'm not sure of it.

Sorry for the inconvenience.

**Comment by felixgilles** [comment]
Good news, no matter :smiley:
