### ISSUE TITLE
Error on migration

### ISSUE THREAD

**Issue by mvy** [novius-os/novius-os#28]
Hi!

I just migrated from master/0.2 to master/chiba this morning. 

I run the instructions given here : http://docs.novius-os.org/en/chiba.1/install/upgrade.html that is to say 

```
git fetch origin
git checkout master/chiba
git merge origin/master/chiba
git submodule update --recursive --init
sudo php oil refine migrate
```

But it seems one table was not migrated correctly as I get an error : 

```
Database configuration error.

Original message: Unknown column 't0.page_publication_start' in 'field list' [ SELECT `t0`.`page_id` AS `t0_c0`, `t0`.`page_parent_id` AS `t0_c1`, `t0`.`page_template` AS `t0_c2`, `t0`.`page_level` AS `t0_c3`, `t0`.`page_title` AS `t0_c4`, `t0`.`page_context` AS `t0_c5`, `t0`.`page_context_common_id` AS `t0_c6`, `t0`.`page_context_is_main` AS `t0_c7`, `t0`.`page_menu_title` AS `t0_c8`, `t0`.`page_meta_title` AS `t0_c9`, `t0`.`page_sort` AS `t0_c10`, `t0`.`page_menu` AS `t0_c11`, `t0`.`page_type` AS `t0_c12`, `t0`.`page_published` AS `t0_c13`, `t0`.`page_publication_start` AS `t0_c14`, `t0`.`page_publication_end` AS `t0_c15`, `t0`.`page_meta_noindex` AS `t0_c16`, `t0`.`page_lock` AS `t0_c17`, `t0`.`page_entrance` AS `t0_c18`, `t0`.`page_home` AS `t0_c19`, `t0`.`page_cache_duration` AS `t0_c20`, `t0`.`page_virtual_name` AS `t0_c21`, `t0`.`page_virtual_url` AS `t0_c22`, `t0`.`page_external_link` AS `t0_c23`, `t0`.`page_external_link_type` AS `t0_c24`, `t0`.`page_created_at` AS `t0_c25`, `t0`.`page_updated_at` AS `t0_c26`, `t0`.`page_meta_description` AS `t0_c27`, `t0`.`page_meta_keywords` AS `t0_c28` FROM `nos_page` AS `t0` WHERE `t0`.`page_context` = 'main::fr_FR' AND `t0`.`page_entrance` = 1 AND (`t0`.`page_published` = '1' OR ((`t0`.`page_published` = 2 AND (`t0`.`page_publication_start` IS null OR `t0`.`page_publication_start` <= NOW()) AND (`t0`.`page_publication_end` IS null OR `t0`.`page_publication_end` >= NOW())))) ORDER BY `t0`.`page_id` ASC LIMIT 1 ]
```

Did the table or column get removed? Edit: or added?

Edit 2: By the way, you said there should be a `public/migrate.php.sample` which is in fact `migrate/htdocs/migrate.php.sample`. But I guess this won't help me anyway since it calls to `migrateAll()` which I feel is the same as the oil migration?

**Comment by sdrdis** [comment]
seems the following line is missing (I will correct that):

```
sudo php oil refine migrate -m
```

Let me know if this works :)

**Comment by mvy** [comment]
Yes, seems the command fixed the problem.

Bonus question: did you happen to make something to the way that the framework provides properties to the templates? My `<?=\Nos\Nos::main_controller()->getPage()->am_style ?>` instruction fails to find my additional column I added to `nos_page`.

**Comment by sdrdis** [comment]
There has been an issue corrected at the end of last week that was making the custom properties not to be fetched on native models. When you say it fails to find your additional column : does it throw an exception, or is the column only empty ?

Thanks,

**Comment by mvy** [comment]
Hum. Seems that's a deeper problem that expected. I'll be back with another issue if necessary.

**Comment by mvy** [comment]
On page load or save: 

```
Property "am_style" not found for Nos\Page\Model_Page.
```

I managed to change my template for my home page and put a notification message while I fix the problem. Translated pages seems to refuse the change by showing the same error. Logs aren't showing many things. 

The thing was working with a `bootstrap.php`  within `local` containing this : 

```
<?php¬
¬
Event::register_function('config|noviusos_page::controller/admin/page', function(&$config) {¬
    $config['fields']['am_style'] = array(¬
        'label' => 'Couleur',¬
        'form' => array(¬
            'type' => 'text',¬
        ),¬
    );¬
    $config['layout']['form']['params']['menu']['ul'] = array(¬
        'title' => 'Ambiant',¬
        'fields' => array('am_style'),¬
    );¬
});¬
¬
Event::register_function('config|noviusos_page::model/page', function(&$config) {¬
    $config['behaviours']['Nos\Orm_Behaviour_Twinnable'] = array(¬
        'invariant_fields' => array('am_style'),¬
    );¬
});
```

**Comment by felixgilles** [comment]
Hi Yves,

Now, in Chiba, models properties are defined in model class. So if you add a custom field to a native model, you have to do something if you want that works, 2 choices:
- add your field to Model_Page properties, by registering an event on config|noviusos_page::model/page

``` php
Event::register_function('config|noviusos_page::model/page', function(&$config) {
    $config['properties']['am_style'] = array();
});
```
- activate the cache mechanism for models properties. That will merge defined properties with the list of fields fetched by a DB request. To activate the cache mechanism, you must set novius-os.cache_model_properties to true in your bootstrap:

``` php
\Config::set('novius-os.cache_model_properties', true);
```

I will completing the documentation for that.

**Comment by mvy** [comment]
Good job! It's working again. I replaced the `Twinnable` section by the one you just gave me and all is running well.

Thanks a lot.
