### ISSUE TITLE
Code profiler

### ISSUE THREAD

**Issue by mvy** [novius-os/novius-os#29]
Hi again.

It seems that the code profiler is running even if I'm not logged in as admin in the backend. 

Is there a way to remove this?

Thanks

**Comment by felixgilles** [comment]
For the moment, we simply use the FuelPHP profiler. In the future, profiling will be part of front features for logged administrators. 

By default, profiling is activate when Fuel::$env === Fuel::DEVELOPMENT 
So if you're site is in production, define Fuel::$env to 'production' (by setting server variable NOS_ENV or Fuel_ENV, or directly in your bootstrap), then the profiling will be disabled. 
You can also enabled or disabled profiling in local/config/config.php, with 'profiling' key (See local/config/config.php.sample)
