### ISSUE TITLE
install: use email when creating the account

### ISSUE THREAD

**Issue by vrcAlbert** [novius-os/novius-os#3]
During the 3rd step, a login has to be chosen. 
It is possible to use a single word (e.g. "admin") whereas an email is needed to log into the administration panel!

**Comment by ounziw** [comment]
Dear vrcAlbert,

Yes, it was a ploblem in the older version.
It seems to be fixed on 0.1alpha, released on March 6.

**Comment by vrcAlbert** [comment]
Thanks for replying, I'll update the project!
