### ISSUE TITLE
Little javascript error when a tab is reloaded

### ISSUE THREAD

**Issue by Foine** [novius-os/novius-os#31]
I have a little (which don't block the system) when I reload a tab (with the right click on a tab)
This is that error : 

``` javascript
TypeError: self.domObject is null
In line 333 of http://my-site.com/static/novius-os/admin/vendor/wijmo/js/wijmenu/jquery.wijmo.wijmenu.js
```

It's not very important but it's always better when there is no little errors that can hide big one ;)

**Comment by felixgilles** [comment]
Thank Foine for the report. It's fixed.
