### ISSUE TITLE
Making Novius-os work on Windows XP and 2000

### ISSUE THREAD

**Issue by Purus** [novius-os/novius-os#34]
I was upset that I can not try this in my Windows XP. After doing some research I found some solution.

Is it possible for your guys to add this to the main script and a note about Junction?

1) Download Junction tool from http://technet.microsoft.com/pl-pl/sysinternals/bb896768.aspx

2) Copy that .exe in c:\windows\system32 or any other place in your %PATH%

2) In novius-os\framework\classes\fuel\File.php file replace 

``` php
  return _symlink($target, $link);
```

with

``` php
if ( OS_WIN){
     return exec('junction "' . $link . '" "' . $target . '"');
}else{
    return _symlink($target, $link);
}
```

**Comment by Purus** [comment]
ça marche pour moi sans erreurs pendant installation mais pour les autres page, non.

**Comment by felixgilles** [comment]
Hi,

Good find Purus. We can, maybe, implement natively, with a try/catch if junction is not install.
But, after install, what are others errors  ?

**Comment by Purus** [comment]
The other error was due to readlink function, which I am sure has some options as before.

**Comment by felixgilles** [comment]
Maybe an exec('readLink') in place of the PHP function readlink ?

**Comment by felixgilles** [comment]
Hi,
- I've tested junction on XP. It works fine directly from CMD but, when I call it from an exec(), exec() never responding. Do you have an idea why ?
- readlink function don't exist on XP but we use it only for verifications. For your test, you can just remove those calls.
- You talk about a <code>return _symlink($target, $link);</code> in novius-os\framework\classes\fuel\File.php: I don't find this line. Which version of Novius OS do you use ?

**Comment by Purus** [comment]
Just curious, why there is lot of dependencies on symlinks?

I will update you on the rest soon.

**Comment by Savageman** [comment]
It works on most systems, that's why we use them. Windows XP is now old and few developers didn't make the update.

**Comment by Purus** [comment]
I agree.. But in countries like India, developers and organizations wont upgrade the OS very often. Its sad that I could not try this script in my Windows XP machine.

**Comment by felixgilles** [comment]
Hi Purus,

Can you test this version of Novius OS: https://github.com/novius-os/novius-os/tree/feature/xp_junction
She contains this version of Core submodule: https://github.com/novius-os/core/compare/rel%2Fd...feature%2Fxp_junction

**Comment by felixgilles** [comment]
You must use git to test this version. If you need a Zip File, tell me, I send it to you.

**Comment by felixgilles** [comment]
I close this issue
Novius OS gave up the idea to support Window XP or 2000
