### ISSUE TITLE
Restoring all symbolic link

### ISSUE THREAD

**Issue by mvy** [novius-os/novius-os#35]
Hi there!

For unfortunate update reasons, I had to backup all my server. In the process I lost the symbolic links of my Novius-OS installation. 

It there a way to restore them quickly? A script or a list of all the needed links somewhere?

Thanks in advance

Yves

**Comment by Savageman** [comment]
Hello :)

The only "required" symbolic link is the one for the core (`public/htdocs/novius-os -> ../../novius-os/htdocs`). From there you should be able to log into the back-office and restore everything else by clicking "Refresh all metadata" in the Application Manager.

I can see 2 solutions for you to restore the link:
1. Do it manually ;
2. Launch install.php (like you did the first time), it will try to recreate the link or give you the appropriate command to do it.

**Comment by mvy** [comment]
Hi again, 

finally got my site working again from the backup. However, admin page won't load 

>  Oops!
> An unexpected error has occurred.

The fuel log indicates: 

>  Error - Could not find asset: login.css in /home/.../novius-os/fuel-core/classes/asset/instance.php on line 249

I deduced rightly that I needed to restore the symbolinc link `public/static/apps/novius-os >  ../../novius-os/static` in addition.

**Comment by Savageman** [comment]
Yup, good thinking. Glad you sorted it out :)
