### ISSUE TITLE
While running home page after making  home page I am getting following issue

### ISSUE THREAD

**Issue by amitkumar1980** [novius-os/novius-os#36]
Cache could not be written! (path = E:\xampp\htdocs\social\local\cache/pages\localhost:4090\social\index.php)

**Comment by felixgilles** [comment]
I guess that Windows don't like the two points in the path. 

Can you try by changing this line: 
https://github.com/novius-os/core/blob/master/chiba2/framework/classes/frontcache.php#L491

By 

```
return 'pages'.DS.str_replace(array('http://', 'https://', ':'), array('', '', ''), rtrim($base, '/')).DS.trim($url, '/');
```
