### ISSUE TITLE
Feature Request - Markdown mode

### ISSUE THREAD

**Issue by dbb** [novius-os/novius-os#38]
I apologize in advance if this has been brought up before. I searched the forums and the ReadTheDocs pages for "markdown" and got 0 results.

I would like to have the option for a "markdown mode" for editing the post body. At present, it seems there is only WYSIWYG and raw HTML. I think using markdown is a fairly standard feature for CMS platforms, at least the ones I've tried.

I don't think it would be necessary to have all three modes available at once (switching between them might be a hassle), but perhaps just an optional mode that allows markdown input -> HTML output or so.

**Comment by felixgilles** [comment]
That would be a great feature.

Unlike other CMS, Novius OS provides a default WYSIWYG for contents. This allows to provide an interface for inserting links pages, media and especially applications. But in some cases, Markdown is so much easier !

A native implementation is possible but not necessarily simple shortly.
The other option is to make a Markdown application, which provides an enhancer Markdown to write markdown in the WYSIWYG. This solution has the merit of being very simple to implement and non-intrusive. Perhaps I'll make it for personal use wink:
