### ISSUE TITLE
Can't redifined an appdesk tab

### ISSUE THREAD

**Issue by Foine** [novius-os/novius-os#39]
Hello,
I tried to edit the tab of an appdesk. To do that, I edit the config file of my appdesk controller.
I add the following code into the configuration array : 

   'appdesk' => array(
        'tab' => array(
            'iconSize' => 16,
            'iconUrl' => 'static/apps/my_app/img/16/icon.png',
            'label' => 'My label',
        ),
    ),

I see the icon and it is at the good size, but the label isn't write beside the icon. Is this a bug or did I do something wrong ?

Thanks in advance for your help.

**Comment by felixgilles** [comment]
Hi @Foine,

Tabs of appdesks are usually 32 pixels size and without label. So if you want to overwrite this behaviour, you have to set `labelDisplay` to true.

**Comment by Foine** [comment]
Thank you @felixgilles ! :)

It works perfectly. I didn't see this option into the API documentation. I must have miss it.

Thank you again.
