### ISSUE TITLE
Can't add an action in an appdesk

### ISSUE THREAD

**Issue by Foine** [novius-os/novius-os#40]
Hello,
I wanted to add an action on an appdesk.
This action have no relation with the model that is show in the appdesk.

I tried this in the appdesk configuration : 

```
$user = Session::user();
$is_expert = $user->user_expert;
if ($is_expert) {
    $action = array(
        'action' => array(
            'action' => 'nosAjax',
            'params' => array(
                'url' => "admin/application/crud/correct_path",
                'method' => 'POST',
                'dataType' => 'json'
            ),
        ),
        'label' => __('Label'),
        'target' => array(
            'toolbar-grid' => true,
        ),
    );

}
```

I tried to add my action in to ways : 

```
 $config['appdesk']['actions']['correct_path'] = $action;
```

and

```
$config['appdesk']['appdesk']['buttons']['correct_path'] = $action;
```

The first way do nothing.
The second way add my action, but the others actions that are added by inspectors, and also a primary action like the add button disappear.

Do you have a clue to add an action on an appdesk without add it in a common configuration of a model ?
Thanks for your help.

**Comment by felixgilles** [comment]
Hi @Foine,

You can try by adding your action in the appdesk config file, in a subkey of toolbar.actions

```
'toolbar' => array(
    'actions' => array(
        'correct_path' = > array(
             'action' => array(
                 'action' => 'nosAjax',
                 'params' => array(
                     'url' => "admin/application/crud/correct_path",
                     'method' => 'POST',
                     'dataType' => 'json'
                ),
            ),
            'label' => __('Label'),
        ),
    ),
),
```

**Comment by felixgilles** [comment]
Hi @Foine 

do you have try with `toolbar` ?

**Comment by Foine** [comment]
Hi @felixgilles 

I just tried that and it works fine. Thank you for your help !
