### ISSUE TITLE
Problem in the "How to install Novius OS"

### ISSUE THREAD

**Issue by Foine** [novius-os/novius-os#6]
Hello.
I have tried to install Novius OS on MAC OS X using the apache server already install on the system.
I follow the instruction and I see that lines : 

<code>
< VirtualHost *:80 >
    DocumentRoot /var/www/novius-os/public
    ServerName   novius-os
    AllowOverride All
</ VirtualHost >
</code>

There is a problem in the "AllowOverride All" line. That command normally go in a Directory node. My apache does not suport that in a VirtualHost (it dont works anymore with it). Without it, everything works great.

It's not a big deal but it's better if the tutorial works without any mistake.

For information : 
Server version: Apache/2.2.21 (Unix)

**Comment by Savageman** [comment]
Hello.

Thank you for helping us with the bugs!

You're totally right, AllowOverride doesn't apply in a <VirtualHost> context.
I just updated the wiki page to make the change.

Does it work for you now? Keep us informed, thanks!
