### ISSUE TITLE
Headers bug - install.php

### ISSUE THREAD

**Issue by marienfressinaud** [novius-os/novius-os#7]
Hello,

I tried to install Novius on my server. The first step is ok, but when I click on "Move on to the next step", I have a warning :

``` Warning!

ErrorException [ Warning ]: Cannot modify header information - headers already sent by (output started at /home/marienfr/public_html/dzoing/sub/novius/public/install.php:138)

DOCROOT/install.php @ line 471
```

I can skip this bug by modifying the url, but it's not really user-friendly ;)

For information, I have :
Apache 2.2.22
PHP 5.3.10

**Comment by marienfressinaud** [comment]
Oh, and it's the same for the end of steps 2 and 3 !

**Comment by Savageman** [comment]
Thanks for reporting it. Oddly enough it was working on our side because we didn't catch it.
