### ISSUE TITLE
Session timeout is not detected

### ISSUE THREAD

**Issue by mvy** [novius-os/novius-os#8]
When the session expires (remember me unchecked), the dashboard raiser an "internal error" popup without any other piece of information.

Hitting F5 brings back the login form. A timeout detection with automatic redirection would be nice.

Edit : the error log

```
PHP Fatal error:  Call to a member function check_permission() on a non-object in /home/.../novius-os/framework/classes/permission.php on line 36, referer: http://.../admin?tab=admin/nos/media/appdesk/index
```

**Comment by Savageman** [comment]
Fixed in the next release.

Thanks for reporting the bug :-)

https://github.com/novius-os/core/commit/2f7348451c64705dba85f82858867687dde774aa
https://github.com/novius-os/core/commit/4503dac6b81a40944e3afb7971b0fcc61153bc21
