### ISSUE TITLE
Missing puclic/media folder permissions

### ISSUE THREAD

**Issue by mvy** [novius-os/novius-os#9]
I had to add: 

```
chmod g+w public
```

To avoid errors in 404.php `mkdir` (around line 71) and possibly the following `symlink` function. Seems this permission was not required at install time.

By the way, my current configuration has all file owned by my username and group www-data.

**Comment by Savageman** [comment]
The installation should take care to handle permissions on every folder Novius OS needs.

The "public" folder should not be made writeable globally. Only a known set of directories are allowed to be modified by the web application.
Do you happen to know which sub-folder was not authorised? The real solution would be to add it into the installation process.

**Comment by mvy** [comment]
Without `public` with the group write permission, the creation of the `/home/.../public/media` fails. The calls were made by `http://.../admin?tab=admin/nos/media/appdesk/index`.

**Comment by Savageman** [comment]
I just checked and you're right. Permissions for public/media are not checked upon installation. We'll update it for the next release and post here when it's done.

Thanks for the bug. :-)
